"""
app/agent.py
============
Core Agent orchestrator that manages:
- Intent understanding (decomposition)
- SQL generation
- Safety validation
- Execution & Self-Correction (max 3 retries)
- Result summarization in natural language
"""

import json
import os
import time
from typing import Dict, Any, Tuple, Optional

import requests
from dotenv import load_dotenv

from app.database import execute_query
from app.validator import validate_sql
from app.logger import get_logger
from app.prompts import (
    SYSTEM_PROMPT,
    DECOMPOSE_PROMPT,
    GENERATE_PROMPT,
    FIX_PROMPT,
    SUMMARY_PROMPT,
)

load_dotenv()

logger = get_logger("SQLAgent")

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "openrouter/auto"
TIMEOUT = 60


def _call_llm(system: str, user_content: str, json_mode: bool = False) -> str:
    """Helper to send a request to OpenRouter completions API."""
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        raise EnvironmentError("OPENROUTER_API_KEY is not configured in .env file.")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload: Dict[str, Any] = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user_content},
        ],
        "temperature": 0.0,
    }
    if json_mode:
        payload["response_format"] = {"type": "json_object"}

    response = requests.post(
        OPENROUTER_URL, headers=headers, json=payload, timeout=TIMEOUT
    )
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"].strip()


def _clean_sql(sql: str) -> str:
    """Remove any accidental markdown fences generated by the model."""
    sql = sql.strip()
    if sql.startswith("```"):
        lines = sql.splitlines()
        inner_lines = [line for line in lines if not line.startswith("```")]
        sql = "\n".join(inner_lines).strip()
    return sql


def _unpack_result(rows: list) -> Any:
    """
    If rows contain a single cell (e.g. COUNT(*)), return the raw value (e.g. 42).
    Otherwise, return the standard list of rows.
    """
    if not rows:
        return []
    if len(rows) == 1:
        row = rows[0]
        if len(row) == 1:
            return list(row.values())[0]
    return rows


class SQLAgent:
    """Self-correcting SQL Agent system."""

    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries

    def run(self, question: str) -> Dict[str, Any]:
        """
        Execute the full Agent loop for a natural language question.
        Returns the final API response.
        """
        agent_start_time = time.perf_counter()
        logger.info(f"--- START SQL AGENT QUERY ---")
        logger.info(f"Question: {question}")

        # ── Step 1: Understand Query (Decomposition) ──────────────────────────
        logger.info("Step 1: Understanding Query (Decomposition)")
        decomp_start = time.perf_counter()
        try:
            decomp_raw = _call_llm(
                system=SYSTEM_PROMPT,
                user_content=f"Decompose this question: {question}\n\nReturn JSON conforming to DECOMPOSE_PROMPT guidelines.",
                json_mode=True,
            )
            decomposition = json.loads(decomp_raw)
            decomp_latency = (time.perf_counter() - decomp_start) * 1000
            logger.info(
                f"Decomposition Step Completed in {decomp_latency:.1f}ms. Intent: {decomposition.get('intent')}"
            )
            logger.info(f"Decomposition data: {json.dumps(decomposition, indent=2)}")
        except Exception as exc:
            logger.error(f"Error during decomposition: {exc}")
            return {
                "sql": None,
                "result": None,
                "summary": "Failed to understand the query structure.",
                "status": "failed",
                "error": f"Decomposition failed: {exc}",
            }

        # ── Step 2: Generate Initial SQL ──────────────────────────────────────
        logger.info("Step 2: Generating initial SQL query")
        sql_gen_start = time.perf_counter()
        try:
            sql_prompt = f"Generate a PostgreSQL SELECT query for this decomposition:\n\n{json.dumps(decomposition, indent=2)}"
            sql_raw = _call_llm(
                system=GENERATE_PROMPT, user_content=sql_prompt, json_mode=False
            )
            current_sql = _clean_sql(sql_raw)
            sql_gen_latency = (time.perf_counter() - sql_gen_start) * 1000
            logger.info(
                f"SQL Generation Step Completed in {sql_gen_latency:.1f}ms. Generated SQL:\n{current_sql}"
            )
        except Exception as exc:
            logger.error(f"Error during SQL generation: {exc}")
            return {
                "sql": None,
                "result": None,
                "summary": "Failed to generate initial SQL query.",
                "status": "failed",
                "error": f"SQL generation failed: {exc}",
            }

        # ── Step 3: Validate & Execute ────────────────────────────────────────
        logger.info("Step 3: Validating and executing SQL")
        is_valid, validation_reason = validate_sql(current_sql)

        db_result = {"columns": [], "rows": [], "row_count": 0, "error": None}
        exec_latency = 0.0

        if not is_valid:
            logger.warning(f"Initial SQL failed validation: {validation_reason}")
            db_result["error"] = f"Validation blocked: {validation_reason}"
        else:
            db_exec_start = time.perf_counter()
            db_result = execute_query(current_sql)
            exec_latency = (time.perf_counter() - db_exec_start) * 1000
            logger.info(
                f"Initial execution completed in {exec_latency:.1f}ms (Rows: {db_result['row_count']})."
            )
            if db_result["error"]:
                logger.error(
                    f"Initial execution returned DB error: {db_result['error']}"
                )

        # ── Step 4: Error Handling & Self-Correction Retry Loop ───────────────
        attempts = 0
        while db_result["error"] is not None and attempts < self.max_retries:
            attempts += 1
            logger.warning(
                f"Step 4: Self-Correction Attempt {attempts}/{self.max_retries}"
            )

            error_message = db_result["error"]
            logger.info(f"Feeding error details back to the LLM to fix the query...")

            fix_start = time.perf_counter()
            try:
                # Fill prompt variables
                fix_prompt = FIX_PROMPT.format(
                    original_sql=current_sql,
                    error_message=error_message,
                    decomposition=json.dumps(decomposition, indent=2),
                )

                fixed_raw = _call_llm(
                    system="You are a PostgreSQL debugging expert.",
                    user_content=fix_prompt,
                    json_mode=False,
                )

                current_sql = _clean_sql(fixed_raw)
                fix_latency = (time.perf_counter() - fix_start) * 1000
                logger.info(
                    f"Self-Correction fix generated in {fix_latency:.1f}ms. Fixed SQL:\n{current_sql}"
                )

                # Re-validate
                is_valid, validation_reason = validate_sql(current_sql)
                if not is_valid:
                    db_result = {
                        "columns": [],
                        "rows": [],
                        "row_count": 0,
                        "error": f"Validation blocked on fix attempt {attempts}: {validation_reason}",
                    }
                    logger.warning(f"Fixed SQL failed validation: {validation_reason}")
                else:
                    # Re-execute
                    db_exec_start = time.perf_counter()
                    db_result = execute_query(current_sql)
                    exec_latency = (time.perf_counter() - db_exec_start) * 1000
                    logger.info(
                        f"Retry {attempts} execution completed in {exec_latency:.1f}ms (Rows: {db_result['row_count']})."
                    )
                    if db_result["error"]:
                        logger.error(
                            f"Retry {attempts} execution returned DB error: {db_result['error']}"
                        )
                    else:
                        logger.info(f"Self-correction succeeded on attempt {attempts}!")
                        break

            except Exception as exc:
                logger.error(
                    f"Failed to generate/execute SQL correction on attempt {attempts}: {exc}"
                )
                db_result["error"] = f"Self-correction routine error: {exc}"

        # ── Step 5: Final Summarization & Output Formulation ─────────────────
        agent_latency = (time.perf_counter() - agent_start_time) * 1000
        logger.info(f"Total Agent latency: {agent_latency:.1f}ms")

        # Fallback if all attempts failed
        if db_result["error"] is not None:
            logger.error(
                "All self-correction attempts failed. Returning fallback response."
            )
            return {
                "sql": current_sql,
                "result": None,
                "summary": "I encountered database connection or syntax errors and could not successfully retrieve the answer. Please try rephrasing your question.",
                "status": "failed",
                "error": db_result["error"],
            }

        # Otherwise, query succeeded! Generate natural language summary
        logger.info("Step 5: Formulating natural language summary")
        summary_start = time.perf_counter()
        try:
            rows_json = json.dumps(db_result["rows"], indent=2, default=str)
            summary_prompt = SUMMARY_PROMPT.format(
                question=question, sql=current_sql, rows_json=rows_json
            )

            summary = _call_llm(
                system="You are a professional database analyst summarizing data reports.",
                user_content=summary_prompt,
                json_mode=False,
            )
            summary_latency = (time.perf_counter() - summary_start) * 1000
            logger.info(
                f"Summary generated in {summary_latency:.1f}ms. Summary:\n{summary}"
            )
        except Exception as exc:
            logger.error(f"Failed to generate summary: {exc}")
            summary = f"Database query completed successfully with {db_result['row_count']} rows returned."

        logger.info(f"--- END SQL AGENT QUERY (Status: success) ---")
        return {
            "sql": current_sql,
            "result": _unpack_result(db_result["rows"]),
            "summary": summary,
            "status": "success",
        }
